default:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
development:
  adapter: mysql2
  database: ipdb_development_seeded
  username: root
production:
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306
