default: &default
  adapter: mysql2
  reconnect: true
  pool: 10
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
development:
  <<: *default
  database: ipdb_development
test:
  <<: *default
  database: ipdb_development_test
production:
  adapter: mysql2
  reconnect: true
  pool: 10
  encoding: utf8
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306
