# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 'cc6060c735dc29cd67329033aa93d4877a8aa7fd6ee758ab940f477fb81a5d193865d5dbd517e562fe29419cfbaa772b3e1f7b9ea556da51c932c813f6b63eca'
  mailgun:
    domain:  <%= ENV['MAILGUN_DOMAIN'] || 'sandbox5d95619b8bec4176b2460f4879db64bc.mailgun.org' %>
    api_key: <%= ENV['MAILGUN_API_KEY'] || 'key-fe2d513b68fa6834a086bb048c7f4fb2' %>
  omniauth:
    facebook_key:    <%= ENV['FACEBOOK_KEY'] || 'facebook_key' %>
    facebook_secret: <%= ENV['FACEBOOK_SECRET'] || 'facebook_secret' %>
  s3:
    access_key_id:     <%= ENV['S3_KEY'] || 's3_key' %>
    secret_access_key: <%= ENV['S3_SECRET'] || 's3_secret' %>
  facebook:
    app_id: '1618263328436021'
  stripe:
    publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] || 'pk_test_GP4q0YqPzL9KZFLAL0iUqFv7' %>
    secret_key:      <%= ENV['STRIPE_SECRET_KEY'] || 'sk_test_1NJZOK43dm9xpi9L5RWX3L37' %>

test:
  secret_key_base: 'cf87b5809f6ced7d9bc335508d25adf71850dfe3ce56a0d9a77b5ed9ffb1304e554d4640391ad3bc3ea3b3a6728cb4f58e6d9a74bc28f12c3dfe13d279f71d4b'
  omniauth:
    facebook_key:    <%= ENV['FACEBOOK_KEY'] || 'facebook_key' %>
    facebook_secret: <%= ENV['FACEBOOK_SECRET'] || 'facebook_secret' %>
  s3:
    access_key_id:     <%= ENV['S3_KEY'] || 's3_key' %>
    secret_access_key: <%= ENV['S3_SECRET'] || 's3_secret' %>
  facebook:
    app_id: '1618263328436021'
  stripe:
    publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] || 'pk_test_GP4q0YqPzL9KZFLAL0iUqFv7' %>
    secret_key:      <%= ENV['STRIPE_SECRET_KEY'] || 'sk_test_1NJZOK43dm9xpi9L5RWX3L37' %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailgun:
    domain:  <%= ENV['MAILGUN_DOMAIN'] %>
    api_key: <%= ENV['MAILGUN_API_KEY'] %>
  omniauth:
    facebook_key:    <%= ENV["FACEBOOK_KEY"] %>
    facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  s3:
    access_key_id:     <%= ENV['S3_KEY'] %>
    secret_access_key: <%= ENV['S3_SECRET'] %>
  facebook:
    app_id: '981327278595983'
  stripe:
    publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
    secret_key:      <%= ENV['STRIPE_SECRET_KEY'] %>
